name: Build image
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}
  argo_version_file: meldingstjeneste-version

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest

    outputs:
      image_url: ${{ steps.setOutput.outputs.image_url }}

    steps:
      - name: Checkout project sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to Github Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }},${{ env.registry }}/${{ github.repository }}:latest

      - name: Set output with build values
        id: setOutput
        run: |
          echo "image_url=${{ env.registry }}/${{ github.repository }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  pharos:
    name: Run Pharos with Required Permissions
    needs: build
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@6515521b3d6b24241fc5508aaf33da692492f4df # v0.4.1
        with:
          image_url: ${{ needs.docker.outputs.image_url}}

  argo:
    name: Update version in apps-repo
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch token
        uses: octo-sts/action@e480437973a6f6ac2e9caa40ecabedc870d76395 # v1.0.1
        id: octo-sts # TODO: Huske Ã¥ legge inn et innslag i .github/chainguard i apps-repo
        with:
          scope: kartverket/egenreg-apps
          identity: meldingstjeneste
      - name: Checkout apps-repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: kartverket/egenreg-apps
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}
      - name: Update version
        run: |
          echo "\"${{ needs.build.outputs.image_url }}\"" > "env/atgcp1-dev/egenreg-main/${{ env.argo_version_file }}"
          git config --global user.email "noreply@kartverket.no"
          git config --global user.name "Egenreg CI"
          git commit -am "Update Egenreg ${{ env.argo_version_file }}"
          git push
